@echo off
pushd %~dp0
set HTTP_PROXY=http://localhost:8123
set HTTPS_PROXY=%HTTP_PROXY%
set NCMB_APPLICATION_KEY=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
set NCMB_CLIENT_KEY=YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
powershell -executionpolicy unrestricted .\ie.ps1
popd
